### ISSUE TITLE
Add Static Page for Organization Chart (Organigramma)

### ISSUE THREAD

**Issue by giobber** [ConoscereLinux/django-conoscerelinux#38]
Two way: 
- add an indipendent static page 
- subclass Generic Static Page (see #37)

## Tasks
- [ ] Add static page for Organization Chart
- [ ] (postponable) Create a role field in member to handle the various role 
- [ ] (postponable) Filter by member.role
